# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  deploy_to_github_pages_on_main_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Publish Message
      run: |-
        echo Publishing the 'build' artifact
  post_deploy_http_call:
    needs:
    - deploy_to_github_pages_on_main_push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Call HTTP endpoint
      run: |-
        curl -X GET 'https://api.findstarlink.com/v1/findstarlink?latitude=20.7984&longitude=-156.3319&numDays=5&pretty' > response.json
    - name: Check HTTP response
      run: |-
        echo "Checking response for string: Honolulu"
        if grep -q "Honolulu" response.json; then
          echo "Response check passed"
        else
          echo "Response check failed"; exit 1
        fi
