# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  post_deploy_http_call:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Call HTTP endpoint
      run: |-
        curl -L -X POST 'https://freebirdxr.com/ops/check-update' -o response.json -w 'Response code: %{response_code}\n' -H "Content-Type: application/json" -d '{"license_num":"TESTabdb-369d-47b9-8d97-3c66b999f29e","update_branch":"main","version":"2.0.0","commit":"fdsfds2d","ref":"bl_start","licensed_device":{"gpu":["Atari","2600"],"cpu":"Intel","ram":"32","os":"Windows"}}'
    - name: Check HTTP response
      run: |-
        echo "Checking response for string: commit"
        if grep -q "commita" response.json; then
          echo "Response check passed"
        else
          echo "Response check failed!"
          echo "Got response:"
          cat response.json
          exit 1
        fi
