# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  deploy_to_github_pages_on_main_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Publish Message
      run: |-
        echo Publishing the 'build' artifact
  post_deploy_http_call:
    needs:
    - deploy_to_github_pages_on_main_push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Call HTTP endpoint
      run: |-
        TEST_BODY='{"license_num":"TESTabdb-369d-47b9-8d97-3c66b999f29e","update_branch":"main","version":"2.0.0","commit":"fdsfds2d","ref":"bl_start","licensed_device":{"gpu":["Atari","2600"],"cpu":"Intel","ram":"32","os":"Windows"}}'
        curl -X POST -H "Content-Type: application/json" -d '$TEST_BODY' 'https://freebirdxr.com/ops/check-update' > response.json
    - name: Check HTTP response
      run: |-
        echo "Checking response for string: commit"
        if grep -q "commit" response.json; then
          echo "Response check passed"
        else
          echo "Response check failed"; exit 1
        fi
