# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |-
        SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)
        echo "Thing is ${{ vars.FOO }} with sha $SHORT_SHA and secret ${{ secrets.FOO_SECRET }}"
