name: CI Pipeline
run-name: CI Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Github release using softprops
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: v1.0.0
        body: Initial release
